### ISSUE TITLE
Rails 5.1 support?

### ISSUE THREAD

**Issue by jarmo** [michelson/espinita#25]
Is there any plans to support Rails 5.1? Currently it does not seem to work by using a non-existing method `before_filter` in https://github.com/continuum/espinita/blob/f7c0c7389917dfcceace435c669427475966635b/lib/espinita/auditor_request.rb - new method is `before_action`.

A workaround is to create an initializer to "monkey-patch" this concern like this:
```ruby
Espinita.send :remove_const, :AuditorRequest

module Espinita::AuditorRequest
  extend ActiveSupport::Concern

  included do
    # originally this line uses method before_filter, which does not exist anymore
    before_action :store_audited_user
  end

  def store_audited_user

    # assign current_user if defined
    RequestStore.store[:audited_user] = self.send(Espinita.current_user_method) if self.respond_to?(Espinita.current_user_method, include_private = true)

    RequestStore.store[:audited_ip]   = self.try(:request).try(:remote_ip)
  end
end
```

**Comment by dubroe** [comment]
+1 to this!

**Comment by michelson** [comment]
this already works! https://github.com/michelson/espinita/blob/master/lib/espinita/auditor_request.rb

**Comment by dubroe** [comment]
Looks like the latest version isn't on Rubygems? https://rubygems.org/gems/espinita
